import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import type { Metadata } from "next";
import { fira } from '@/app/ui/fonts';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className}>{children}</body>
    </html>
  );
}
